const os = require("os");
const path = require("path");
const fs = require("fs/promises");
const { spawnSync } = require("child_process");
const {
  initProfessionalDocs,
  runProfessionalCommand,
  scanProfessionalDocs,
  verifyProfessionalDocs,
} = require("./lib/professional-docs");
const { GENERATED_MARKER } = require("./lib/professional-docs-writer");

const HAND_WRITTEN = "# Onboarding\n\nAsk the platform team for access.\n";

async function write(root, file, body) {
  await fs.mkdir(path.dirname(path.join(root, file)), { recursive: true });
  await fs.writeFile(path.join(root, file), body);
}

const read = (root, file) => fs.readFile(path.join(root, file), "utf8");
const readStatus = async (root) =>
  JSON.parse(await read(root, ".xfeat/status.json"));

describe("Professional docs scan file ownership", () => {
  let workspace;

  beforeEach(async () => {
    workspace = await fs.mkdtemp(path.join(os.tmpdir(), "xfeat-ownership-"));
    await write(
      workspace,
      "package.json",
      JSON.stringify({ name: "billing", scripts: { test: "jest" } }, null, 2),
    );
    await write(
      workspace,
      "src/billing.js",
      "export function charge() {\n  return 1;\n}\n",
    );
    await write(workspace, "README.md", "# Billing\n\nCharges accounts.\n");
  });

  afterEach(async () => {
    await fs.rm(workspace, { recursive: true, force: true });
  });

  it("starts every generated Markdown file with the generator marker", async () => {
    const scan = await scanProfessionalDocs(workspace);

    expect(scan.skipped).toEqual([]);
    for (const doc of [...scan.documents, "xfeat-report.md"]) {
      const text = await read(workspace, doc);
      expect(text.split("\n")[0]).toBe(GENERATED_MARKER);
    }
  });

  it("skips hand-written files at generated paths and reports them", async () => {
    await write(workspace, "docs/onboarding.md", HAND_WRITTEN);
    await write(workspace, "docs/how-to/test.md", "# Testing\n\nRun it.\n");

    const scan = await scanProfessionalDocs(workspace);
    const status = await readStatus(workspace);
    const report = await read(workspace, "xfeat-report.md");

    expect(await read(workspace, "docs/onboarding.md")).toBe(HAND_WRITTEN);
    expect(scan.skipped).toEqual([
      { path: "docs/how-to/test.md", reason: "not generated by xfeat" },
      { path: "docs/onboarding.md", reason: "not generated by xfeat" },
    ]);
    expect(scan.documents).not.toContain("docs/onboarding.md");
    expect(status.documents).not.toContain("docs/onboarding.md");
    expect(status.documents).toContain("docs/architecture/overview.md");
    expect(report).toContain("- Skipped files: 2");
    expect(report).toContain("`docs/onboarding.md` (not generated by xfeat)");
    expect((await verifyProfessionalDocs(workspace)).ok).toBe(true);
  });

  it("overwrites marked files on the next scan", async () => {
    await scanProfessionalDocs(workspace);
    await write(
      workspace,
      "src/ledger.js",
      "export function recordCharge() {\n  return 2;\n}\n",
    );

    const scan = await scanProfessionalDocs(workspace);
    const symbols = await read(workspace, "docs/reference/symbols.md");

    expect(scan.skipped).toEqual([]);
    expect(symbols).toContain("recordCharge");
  });

  it("overwrites pages an earlier scan wrote before markers existed", async () => {
    // Exact openings of pre-marker pages; no .xfeat/status.json is needed.
    await write(
      workspace,
      "docs/onboarding.md",
      "# Onboarding\n\nStart here when joining the repository or preparing a code change.\n\n## Start Here\n",
    );
    await write(
      workspace,
      "docs/reference/files.md",
      "# Files Reference\n\nComplete source-file inventory scanned by `xfeat scan`.\n",
    );
    await write(
      workspace,
      "xfeat-report.md",
      "# xfeat Report\n\n- Source files: 1\n",
    );

    const scan = await scanProfessionalDocs(workspace);

    expect(scan.skipped).toEqual([]);
    for (const doc of [
      "docs/onboarding.md",
      "docs/reference/files.md",
      "xfeat-report.md",
    ]) {
      expect(await read(workspace, doc)).toMatch(/^<!-- xfeat:generated/);
    }
  });

  it("keeps a hand-written page even when an old status file lists it", async () => {
    await write(workspace, "docs/onboarding.md", HAND_WRITTEN);
    await write(
      workspace,
      ".xfeat/status.json",
      JSON.stringify({ documents: ["docs/onboarding.md"], claims: [] }),
    );

    const scan = await scanProfessionalDocs(workspace);

    expect(await read(workspace, "docs/onboarding.md")).toBe(HAND_WRITTEN);
    expect(scan.skipped).toEqual([
      { path: "docs/onboarding.md", reason: "not generated by xfeat" },
    ]);
  });

  it("keeps a generated file once its marker line is deleted", async () => {
    await scanProfessionalDocs(workspace);
    const generated = await read(workspace, "docs/onboarding.md");
    const owned = `${generated.split("\n").slice(1).join("\n")}\nTeam notes.\n`;
    await write(workspace, "docs/onboarding.md", owned);

    const scan = await scanProfessionalDocs(workspace);

    expect(await read(workspace, "docs/onboarding.md")).toBe(owned);
    expect(scan.skipped).toEqual([
      { path: "docs/onboarding.md", reason: "not generated by xfeat" },
    ]);
  });

  it("never writes through symbolic links or into directories", async () => {
    const outside = path.join(workspace, "outside.md");
    await write(workspace, "outside.md", HAND_WRITTEN);
    await fs.mkdir(path.join(workspace, "docs"), { recursive: true });
    await fs.symlink(outside, path.join(workspace, "docs", "onboarding.md"));
    await fs.mkdir(path.join(workspace, "docs", "adr-index.md"));

    const scan = await scanProfessionalDocs(workspace);

    expect(await fs.readFile(outside, "utf8")).toBe(HAND_WRITTEN);
    expect(scan.skipped).toEqual([
      { path: "docs/adr-index.md", reason: "not a regular file" },
      { path: "docs/onboarding.md", reason: "not a regular file" },
    ]);
  });

  it("never writes through a symbolic link to a folder outside the repository", async () => {
    const outside = await fs.mkdtemp(path.join(os.tmpdir(), "xfeat-outside-"));
    await fs.mkdir(path.join(workspace, "docs"), { recursive: true });
    await fs.symlink(outside, path.join(workspace, "docs", "reference"));

    try {
      const scan = await scanProfessionalDocs(workspace);

      expect(await fs.readdir(outside)).toEqual([]);
      expect(scan.skipped.map((item) => item.path)).toEqual([
        "docs/reference",
        "docs/reference/claims.md",
        "docs/reference/files.md",
        "docs/reference/import-graph.md",
        "docs/reference/symbols.md",
      ]);
      expect(scan.skipped[0].reason).toBe("resolves outside the repository");
    } finally {
      await fs.rm(outside, { recursive: true, force: true });
    }
  });

  it("never writes scan state or folders through links that leave the repository", async () => {
    const outside = await fs.mkdtemp(path.join(os.tmpdir(), "xfeat-outside-"));
    const secret = path.join(outside, "bashrc");
    await fs.writeFile(secret, "export PATH=/usr/bin\n");
    await fs.mkdir(path.join(workspace, ".xfeat"), { recursive: true });
    await fs.symlink(secret, path.join(workspace, ".xfeat", "status.json"));
    await fs.symlink(
      path.join(outside, "config.yml"),
      path.join(workspace, ".xfeat.yml"),
    );
    await fs.mkdir(path.join(outside, "docs"));
    await fs.symlink(path.join(outside, "docs"), path.join(workspace, "docs"));

    try {
      const scan = await scanProfessionalDocs(workspace);

      expect(await fs.readFile(secret, "utf8")).toBe("export PATH=/usr/bin\n");
      expect(await fs.readdir(outside)).toEqual(["bashrc", "docs"]);
      expect(await fs.readdir(path.join(outside, "docs"))).toEqual([]);
      expect(scan.documents).toEqual([]);
      expect(scan.skipped).toEqual(
        expect.arrayContaining([
          {
            path: ".xfeat/status.json",
            reason: "resolves outside the repository",
          },
          {
            path: "docs/architecture",
            reason: "resolves outside the repository",
          },
          {
            path: "docs/architecture/overview.md",
            reason: "resolves outside the repository",
          },
        ]),
      );
    } finally {
      await fs.rm(outside, { recursive: true, force: true });
    }
  });

  it("initializes a new project below a symlinked parent folder", async () => {
    const real = await fs.mkdtemp(path.join(os.tmpdir(), "xfeat-real-"));
    const link = path.join(workspace, "linked-parent");
    await fs.symlink(real, link);

    try {
      const init = await initProfessionalDocs(path.join(link, "newproj"));

      expect(init.skipped).toEqual([]);
      expect(init.createdConfig).toBe(true);
      expect(
        (await fs.readdir(path.join(real, "newproj", "docs"))).sort(),
      ).toEqual(["architecture", "components", "how-to", "reference"]);
    } finally {
      await fs.rm(real, { recursive: true, force: true });
    }
  });

  it("exits nonzero and warns when a path resolves outside the repository", async () => {
    const outside = await fs.mkdtemp(path.join(os.tmpdir(), "xfeat-outside-"));
    await fs.mkdir(path.join(workspace, "docs"), { recursive: true });
    await fs.symlink(outside, path.join(workspace, "docs", "reference"));
    const warnings = [];

    try {
      const result = await runProfessionalCommand(["scan", workspace], {
        stdout: () => {},
        stderr: (line) => warnings.push(line),
      });

      expect(result.exitCode).toBe(1);
      expect(warnings).toHaveLength(1);
      expect(warnings[0]).toMatch(
        /^xfeat scan skipped 5 paths: docs\/reference \(resolves outside the repository\)/,
      );
    } finally {
      await fs.rm(outside, { recursive: true, force: true });
    }
  });

  it("never reads source files through links that leave the repository", async () => {
    const outside = await fs.mkdtemp(path.join(os.tmpdir(), "xfeat-outside-"));
    await fs.writeFile(
      path.join(outside, "secret.js"),
      'export const TOKEN = "ghp_outsideRepositoryToken";\n',
    );
    await fs.symlink(
      path.join(outside, "secret.js"),
      path.join(workspace, "src", "linked.js"),
    );
    await fs.symlink(outside, path.join(workspace, "vendor-link"));

    try {
      const scan = await scanProfessionalDocs(workspace);
      const files = scan.facts.map((fact) => fact.file);
      const pages = await Promise.all(
        scan.documents.map((doc) => read(workspace, doc)),
      );

      expect(files).toEqual(["src/billing.js"]);
      expect(pages.join("\n")).not.toContain("ghp_outsideRepositoryToken");
    } finally {
      await fs.rm(outside, { recursive: true, force: true });
    }
  });

  it("prints complete scan JSON through a pipe without source text", async () => {
    for (let index = 0; index < 120; index += 1) {
      await write(
        workspace,
        `src/module${index}.js`,
        `export function handleBillingEvent${index}() {\n  return ${index};\n}\n`,
      );
    }
    await write(workspace, "docs/onboarding.md", HAND_WRITTEN);

    const result = spawnSync(
      process.execPath,
      [path.join(__dirname, "index.js"), "scan", workspace],
      { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
    );
    const output = JSON.parse(result.stdout);

    expect(result.status).toBe(0);
    expect(output.skipped).toEqual([
      { path: "docs/onboarding.md", reason: "not generated by xfeat" },
    ]);
    expect(output.facts.length).toBeGreaterThan(120);
    expect(output.facts.some((fact) => "text" in fact)).toBe(false);
  });

  it("reports an unreadable status as a verify finding instead of crashing", async () => {
    await scanProfessionalDocs(workspace);
    await write(workspace, ".xfeat/status.json", '{ "documents": [');

    const verify = await verifyProfessionalDocs(workspace);

    expect(verify.ok).toBe(false);
    expect(verify.findings).toEqual([
      { type: "invalid-status", path: ".xfeat/status.json" },
    ]);
  });

  it("includes skipped files in the CLI JSON result", async () => {
    await write(workspace, "docs/onboarding.md", HAND_WRITTEN);
    const lines = [];
    const warnings = [];

    const result = await runProfessionalCommand(["scan", workspace], {
      stdout: (line) => lines.push(line),
      stderr: (line) => warnings.push(line),
    });

    expect(result.exitCode).toBe(0);
    expect(warnings).toEqual([
      "xfeat scan skipped 1 path: docs/onboarding.md (not generated by xfeat)",
    ]);
    expect(JSON.parse(lines.join("\n")).skipped).toEqual([
      { path: "docs/onboarding.md", reason: "not generated by xfeat" },
    ]);
  });
});
