const fs = require("fs/promises");
const path = require("path");
const { GENERATOR } = require("./portfolio-links");

// Non-Markdown files xfeat generates. Markdown pages are recognized by the
// generator marker in their frontmatter instead.
const GENERATED_ASSETS = new Set([
  "llms.txt",
  "portfolio.json",
  "diagrams/landscape.puml",
  "diagrams/landscape.svg",
]);

function isInside(child, parent) {
  const relative = path.relative(parent, child);
  return (
    relative === "" ||
    (!relative.startsWith("..") && !path.isAbsolute(relative))
  );
}

async function realpathOrNull(target) {
  try {
    return await fs.realpath(target);
  } catch {
    return null;
  }
}

// Resolves symlinks in the longest existing prefix of `target` without
// creating anything, so containment can be checked before the first mkdir.
async function projectedRealPath(target) {
  const missing = [];
  let current = path.resolve(target);
  for (;;) {
    const real = await realpathOrNull(current);
    if (real) return path.join(real, ...missing.reverse());
    const parent = path.dirname(current);
    if (parent === current) return path.resolve(target);
    missing.push(path.basename(current));
    current = parent;
  }
}

// Writes a generated file, refusing any path that resolves outside the real
// output folder, including through symlinked subfolders.
async function writeInside(realOut, relativeFile, body) {
  const target = path.join(realOut, relativeFile);
  if (!isInside(target, realOut)) {
    throw new Error(
      `Refusing to write ${relativeFile} outside the output folder.`,
    );
  }
  await fs.mkdir(path.dirname(target), { recursive: true });
  const realParent = await realpathOrNull(path.dirname(target));
  const realTarget = await realpathOrNull(target);
  if (
    !realParent ||
    !isInside(realParent, realOut) ||
    (realTarget && !isInside(realTarget, realOut))
  ) {
    throw new Error(
      `Refusing to write ${relativeFile}: it resolves outside the output folder ${realOut}.`,
    );
  }
  await fs.writeFile(target, body, "utf8");
}

// Removes a page left by an earlier scan only when it is still inside the real
// output folder and is recognizably generated by xfeat. Hand-written files are
// kept even when an old portfolio.json lists them.
async function removeGenerated(realOut, relativeFile) {
  const target = path.join(realOut, relativeFile);
  if (!isInside(target, realOut)) return false;
  const real = await realpathOrNull(target);
  if (!real || !isInside(real, realOut)) return false;
  if (relativeFile.endsWith(".md")) {
    const head = (await fs.readFile(real, "utf8")).slice(0, 400);
    if (
      !head.startsWith("---\n") ||
      !head.includes(`generator: ${GENERATOR}`)
    ) {
      return false;
    }
  } else if (!GENERATED_ASSETS.has(relativeFile)) {
    return false;
  }
  await fs.rm(real);
  return true;
}

module.exports = {
  isInside,
  projectedRealPath,
  realpathOrNull,
  removeGenerated,
  writeInside,
};
